spring.application.name=CadastroDeNinjas

# Configurações do Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configurações do Banco de Dados em Memória
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update